# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'munientry/views/ui/HemmeterWorkflowDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HemmeterWorkflowDialog(object):
    def setupUi(self, HemmeterWorkflowDialog):
        HemmeterWorkflowDialog.setObjectName("HemmeterWorkflowDialog")
        HemmeterWorkflowDialog.setWindowModality(QtCore.Qt.WindowModal)
        HemmeterWorkflowDialog.resize(1071, 474)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(HemmeterWorkflowDialog.sizePolicy().hasHeightForWidth())
        HemmeterWorkflowDialog.setSizePolicy(sizePolicy)
        HemmeterWorkflowDialog.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        HemmeterWorkflowDialog.setFont(font)
        HemmeterWorkflowDialog.setStyleSheet("background-color: rgb(25, 49, 91);\n"
"font: 75 11pt \"Palatino Linotype\";")
        self.gridLayout = QtWidgets.QGridLayout(HemmeterWorkflowDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(HemmeterWorkflowDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.frame_3.setFont(font)
        self.frame_3.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"font-weight: bold;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setVerticalSpacing(60)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pending_entries_listWidget = QtWidgets.QListWidget(self.frame_3)
        self.pending_entries_listWidget.setObjectName("pending_entries_listWidget")
        self.gridLayout_2.addWidget(self.pending_entries_listWidget, 1, 0, 2, 1)
        self.show_docket_Button = QtWidgets.QPushButton(self.frame_3)
        self.show_docket_Button.setStyleSheet("background-color: rgb(160, 160, 160);\n"
"font-weight: bold;")
        self.show_docket_Button.setObjectName("show_docket_Button")
        self.gridLayout_2.addWidget(self.show_docket_Button, 1, 1, 1, 1)
        self.open_entry_Button = QtWidgets.QPushButton(self.frame_3)
        self.open_entry_Button.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"font: 75 11pt \"Palatino Linotype\";\n"
"font-weight: bold;")
        self.open_entry_Button.setObjectName("open_entry_Button")
        self.gridLayout_2.addWidget(self.open_entry_Button, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 2)
        self.gridLayout_2.setColumnStretch(0, 3)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(HemmeterWorkflowDialog)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.frame.setFont(font)
        self.frame.setStyleSheet("font: 75 11pt \"Palatino Linotype\";\n"
"font-weight: bold;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cancel_Button = QtWidgets.QPushButton(self.frame)
        self.cancel_Button.setStyleSheet("background-color: rgb(160, 160, 160);\n"
"font-weight: bold;")
        self.cancel_Button.setObjectName("cancel_Button")
        self.gridLayout_4.addWidget(self.cancel_Button, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 4)
        self.gridLayout.setRowStretch(1, 1)

        self.retranslateUi(HemmeterWorkflowDialog)
        QtCore.QMetaObject.connectSlotsByName(HemmeterWorkflowDialog)

    def retranslateUi(self, HemmeterWorkflowDialog):
        _translate = QtCore.QCoreApplication.translate
        HemmeterWorkflowDialog.setWindowTitle(_translate("HemmeterWorkflowDialog", "Judge Hemmeter Digital Workflow"))
        self.show_docket_Button.setText(_translate("HemmeterWorkflowDialog", "Show Case Docket"))
        self.open_entry_Button.setText(_translate("HemmeterWorkflowDialog", "Open Entry for Review"))
        self.label.setText(_translate("HemmeterWorkflowDialog", "<html><head/><body><p><span style=\" text-decoration: underline;\">ENTRIES PENDING REVIEW</span></p></body></html>"))
        self.cancel_Button.setText(_translate("HemmeterWorkflowDialog", "Cancel"))
