# Form implementation generated from reading ui file 'munientry/views/ui/PretrialWorkflowDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PretrialWorkflowDialog(object):
    def setupUi(self, PretrialWorkflowDialog):
        PretrialWorkflowDialog.setObjectName("PretrialWorkflowDialog")
        PretrialWorkflowDialog.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        PretrialWorkflowDialog.resize(1006, 828)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PretrialWorkflowDialog.sizePolicy().hasHeightForWidth())
        PretrialWorkflowDialog.setSizePolicy(sizePolicy)
        PretrialWorkflowDialog.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        PretrialWorkflowDialog.setFont(font)
        PretrialWorkflowDialog.setStyleSheet("background-color: rgb(25, 49, 91);\n"
"font: 75 11pt \"Palatino Linotype\";")
        self.gridLayout = QtWidgets.QGridLayout(PretrialWorkflowDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(PretrialWorkflowDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.frame_3.setFont(font)
        self.frame_3.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"font-weight: bold;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setVerticalSpacing(24)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line_2 = QtWidgets.QFrame(self.frame_3)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 6, 0, 1, 2)
        self.open_entry_Button = QtWidgets.QPushButton(self.frame_3)
        self.open_entry_Button.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"font: 75 11pt \"Palatino Linotype\";\n"
"font-weight: bold;")
        self.open_entry_Button.setObjectName("open_entry_Button")
        self.gridLayout_2.addWidget(self.open_entry_Button, 7, 1, 1, 1)
        self.load_new_entries_Button = QtWidgets.QPushButton(self.frame_3)
        self.load_new_entries_Button.setStyleSheet("background-color: rgb(160, 160, 160);\n"
"font-weight: bold;")
        self.load_new_entries_Button.setObjectName("load_new_entries_Button")
        self.gridLayout_2.addWidget(self.load_new_entries_Button, 7, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 2)
        self.close_dialog_Button = QtWidgets.QPushButton(self.frame_3)
        self.close_dialog_Button.setStyleSheet("background-color: rgb(160, 160, 160);\n"
"font-weight: bold;")
        self.close_dialog_Button.setObjectName("close_dialog_Button")
        self.gridLayout_2.addWidget(self.close_dialog_Button, 8, 0, 1, 1)
        self.delete_entry_Button = QtWidgets.QPushButton(self.frame_3)
        self.delete_entry_Button.setStyleSheet("background-color: rgb(255, 96, 82);\n"
"font: 75 11pt \"Palatino Linotype\";\n"
"font-weight: bold;")
        self.delete_entry_Button.setObjectName("delete_entry_Button")
        self.gridLayout_2.addWidget(self.delete_entry_Button, 8, 1, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_3)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_2.addWidget(self.textBrowser, 1, 0, 1, 2)
        self.entries_tableWidget = QtWidgets.QTableWidget(self.frame_3)
        self.entries_tableWidget.setObjectName("entries_tableWidget")
        self.entries_tableWidget.setColumnCount(0)
        self.entries_tableWidget.setRowCount(0)
        self.gridLayout_2.addWidget(self.entries_tableWidget, 2, 0, 1, 2)
        self.gridLayout_2.setRowStretch(2, 5)
        self.gridLayout.addWidget(self.frame_3, 0, 0, 1, 2)
        self.gridLayout.setRowStretch(0, 4)

        self.retranslateUi(PretrialWorkflowDialog)
        QtCore.QMetaObject.connectSlotsByName(PretrialWorkflowDialog)

    def retranslateUi(self, PretrialWorkflowDialog):
        _translate = QtCore.QCoreApplication.translate
        PretrialWorkflowDialog.setWindowTitle(_translate("PretrialWorkflowDialog", "Pretrial Workflow"))
        self.open_entry_Button.setText(_translate("PretrialWorkflowDialog", "Open Selected Entry for Review"))
        self.load_new_entries_Button.setText(_translate("PretrialWorkflowDialog", "Check For New Entries"))
        self.label.setText(_translate("PretrialWorkflowDialog", "<html><head/><body><p><span style=\" text-decoration: underline;\">PRETRIAL ENTRIES</span></p></body></html>"))
        self.close_dialog_Button.setText(_translate("PretrialWorkflowDialog", "Close Workflow"))
        self.delete_entry_Button.setText(_translate("PretrialWorkflowDialog", "Delete Entry from Workflow"))
        self.textBrowser.setHtml(_translate("PretrialWorkflowDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Palatino Linotype\'; font-size:11pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The list below contains draft versions of entries for any entry that imposes or modifies a bond <span style=\" text-decoration: underline;\">and</span><span style=\" font-weight:400;\"> </span>that meets at least one of the following conditions:</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1. All TRC cases (i.e. all OVI cases).</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2. Case types CRB or TRD where monitoring is imposed - SCRAM, GPS, Alcohol Kiosk.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3. Case types CRB or TRD where an alcohol assessment, mental health assessment or specialized docket screening is ordered.</p></body></html>"))
