# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/JuryInstructionsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JuryInstructionsDialog(object):
    def setupUi(self, JuryInstructionsDialog):
        JuryInstructionsDialog.setObjectName("JuryInstructionsDialog")
        JuryInstructionsDialog.resize(483, 359)
        self.layoutWidget = QtWidgets.QWidget(JuryInstructionsDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 281, 52))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.CaseNo_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.CaseNo_lineEdit.setObjectName("CaseNo_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.CaseNo_lineEdit)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.DefendantName_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.DefendantName_lineEdit.setObjectName("DefendantName_lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.DefendantName_lineEdit)
        self.layoutWidget1 = QtWidgets.QWidget(JuryInstructionsDialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(370, 10, 95, 147))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(20, 58, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.layoutWidget2 = QtWidgets.QWidget(JuryInstructionsDialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 80, 321, 171))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.dateEdit = QtWidgets.QDateEdit(self.layoutWidget2)
        self.dateEdit.setObjectName("dateEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.firstCharge_comboBox = QtWidgets.QComboBox(self.layoutWidget2)
        self.firstCharge_comboBox.setObjectName("firstCharge_comboBox")
        self.firstCharge_comboBox.addItem("")
        self.firstCharge_comboBox.addItem("")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.firstCharge_comboBox)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.secondCharge_comboBox = QtWidgets.QComboBox(self.layoutWidget2)
        self.secondCharge_comboBox.setObjectName("secondCharge_comboBox")
        self.secondCharge_comboBox.addItem("")
        self.secondCharge_comboBox.addItem("")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.secondCharge_comboBox)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.radioButton = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(JuryInstructionsDialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton)
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.radioButton_2)

        self.retranslateUi(JuryInstructionsDialog)
        self.pushButton_3.clicked.connect(JuryInstructionsDialog.reject)
        self.pushButton_2.clicked.connect(self.CaseNo_lineEdit.clear)
        self.pushButton_2.clicked.connect(self.DefendantName_lineEdit.clear)
        self.pushButton.clicked.connect(JuryInstructionsDialog.createEntry)
        QtCore.QMetaObject.connectSlotsByName(JuryInstructionsDialog)

    def retranslateUi(self, JuryInstructionsDialog):
        _translate = QtCore.QCoreApplication.translate
        JuryInstructionsDialog.setWindowTitle(_translate("JuryInstructionsDialog", "Jury Instructions"))
        self.label.setText(_translate("JuryInstructionsDialog", "Case No."))
        self.label_2.setText(_translate("JuryInstructionsDialog", "Defendant Name: "))
        self.pushButton.setText(_translate("JuryInstructionsDialog", "Create Entry"))
        self.pushButton_2.setText(_translate("JuryInstructionsDialog", "Clear Fields"))
        self.pushButton_3.setText(_translate("JuryInstructionsDialog", "Cancel"))
        self.label_3.setText(_translate("JuryInstructionsDialog", "Complaint Date"))
        self.label_4.setText(_translate("JuryInstructionsDialog", "1st Charge"))
        self.firstCharge_comboBox.setItemText(0, _translate("JuryInstructionsDialog", "Operating a Motor Vehicle While Under the Influence of Alcohol \n"
"R.C. § 4511.19(A)(1)(A)\n"
""))
        self.firstCharge_comboBox.setItemText(1, _translate("JuryInstructionsDialog", "Operating a Motor Vehicle with a Prohibited Concentration of Alcohol \n"
"R.C. § 4511.19(A)(1)(D)\n"
""))
        self.label_5.setText(_translate("JuryInstructionsDialog", "2nd Charge"))
        self.secondCharge_comboBox.setItemText(0, _translate("JuryInstructionsDialog", "Operating a Motor Vehicle While Under the Influence of Alcohol \n"
"R.C. § 4511.19(A)(1)(A)\n"
""))
        self.secondCharge_comboBox.setItemText(1, _translate("JuryInstructionsDialog", "Operating a Motor Vehicle with a Prohibited Concentration of Alcohol \n"
"R.C. § 4511.19(A)(1)(D)\n"
""))
        self.label_6.setText(_translate("JuryInstructionsDialog", "Victim Name"))
        self.radioButton.setText(_translate("JuryInstructionsDialog", "Defendant Testified"))
        self.radioButton_2.setText(_translate("JuryInstructionsDialog", "Defendant Did Not Testify"))
