# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/TransferEntryDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TransferEntryDialog(object):
    def setupUi(self, TransferEntryDialog):
        TransferEntryDialog.setObjectName("TransferEntryDialog")
        TransferEntryDialog.resize(579, 438)
        self.layoutWidget_2 = QtWidgets.QWidget(TransferEntryDialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(460, 20, 95, 151))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(20, 58, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.layoutWidget = QtWidgets.QWidget(TransferEntryDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(5, 15, 391, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(5, 5, 5, 5)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)

        self.retranslateUi(TransferEntryDialog)
        QtCore.QMetaObject.connectSlotsByName(TransferEntryDialog)

    def retranslateUi(self, TransferEntryDialog):
        _translate = QtCore.QCoreApplication.translate
        TransferEntryDialog.setWindowTitle(_translate("TransferEntryDialog", "Transfer Entry Dialog"))
        self.pushButton.setText(_translate("TransferEntryDialog", "Create Entry"))
        self.pushButton_2.setText(_translate("TransferEntryDialog", "Clear Fields"))
        self.pushButton_3.setText(_translate("TransferEntryDialog", "Cancel"))
        self.label.setText(_translate("TransferEntryDialog", "Defendant Name:"))
        self.label_2.setText(_translate("TransferEntryDialog", "Case No.:"))
