# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/VerdictFormDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VerdictFormDialog(object):
    def setupUi(self, VerdictFormDialog):
        VerdictFormDialog.setObjectName("VerdictFormDialog")
        VerdictFormDialog.resize(579, 438)
        self.layoutWidget_2 = QtWidgets.QWidget(VerdictFormDialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(460, 20, 95, 151))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(20, 58, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.layoutWidget = QtWidgets.QWidget(VerdictFormDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(5, 15, 391, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(5, 5, 5, 5)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.defendant_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.defendant_name.setObjectName("defendant_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.defendant_name)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.case_no = QtWidgets.QLineEdit(self.layoutWidget)
        self.case_no.setObjectName("case_no")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.case_no)

        self.retranslateUi(VerdictFormDialog)
        self.pushButton.clicked.connect(VerdictFormDialog.createEntry)
        QtCore.QMetaObject.connectSlotsByName(VerdictFormDialog)

    def retranslateUi(self, VerdictFormDialog):
        _translate = QtCore.QCoreApplication.translate
        VerdictFormDialog.setWindowTitle(_translate("VerdictFormDialog", "Dialog"))
        self.pushButton.setText(_translate("VerdictFormDialog", "Create Entry"))
        self.pushButton_2.setText(_translate("VerdictFormDialog", "Clear Fields"))
        self.pushButton_3.setText(_translate("VerdictFormDialog", "Cancel"))
        self.label.setText(_translate("VerdictFormDialog", "Defendant Name:"))
        self.label_2.setText(_translate("VerdictFormDialog", "Case No.:"))
