# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/VerdictFormDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VerdictFormDialog(object):
    def setupUi(self, VerdictFormDialog):
        VerdictFormDialog.setObjectName("VerdictFormDialog")
        VerdictFormDialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(VerdictFormDialog)
        self.buttonBox.setGeometry(QtCore.QRect(290, 20, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(VerdictFormDialog)
        self.buttonBox.accepted.connect(VerdictFormDialog.accept)
        self.buttonBox.rejected.connect(VerdictFormDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(VerdictFormDialog)

    def retranslateUi(self, VerdictFormDialog):
        _translate = QtCore.QCoreApplication.translate
        VerdictFormDialog.setWindowTitle(_translate("VerdictFormDialog", "Dialog"))
