# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views\ui\CollapsibleTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(809, 490)
        self.treeWidget = QtWidgets.QTreeWidget(Form)
        self.treeWidget.setGeometry(QtCore.QRect(120, 90, 256, 192))
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.treeView = QtWidgets.QTreeView(Form)
        self.treeView.setGeometry(QtCore.QRect(460, 120, 256, 192))
        self.treeView.setObjectName("treeView")
        self.treeWidget_2 = QtWidgets.QTreeWidget(Form)
        self.treeWidget_2.setGeometry(QtCore.QRect(50, 290, 256, 192))
        self.treeWidget_2.setObjectName("treeWidget_2")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.treeWidget_2.headerItem().setText(0, _translate("Form", "1"))
        __sortingEnabled = self.treeWidget_2.isSortingEnabled()
        self.treeWidget_2.setSortingEnabled(False)
        self.treeWidget_2.topLevelItem(0).setText(0, _translate("Form", "TEST"))
        self.treeWidget_2.topLevelItem(0).child(0).setText(0, _translate("Form", "Test1"))
        self.treeWidget_2.topLevelItem(0).child(1).setText(0, _translate("Form", "Test2"))
        self.treeWidget_2.topLevelItem(1).setText(0, _translate("Form", "TEST @"))
        self.treeWidget_2.topLevelItem(1).child(0).setText(0, _translate("Form", "TEST 1"))
        self.treeWidget_2.topLevelItem(1).child(1).setText(0, _translate("Form", "TEST @"))
        self.treeWidget_2.setSortingEnabled(__sortingEnabled)
