# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\AbilityToPayDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AbilityToPayDialog(object):
    def setupUi(self, AbilityToPayDialog):
        AbilityToPayDialog.setObjectName("AbilityToPayDialog")
        AbilityToPayDialog.resize(659, 370)
        self.pushButton_2 = QtWidgets.QPushButton(AbilityToPayDialog)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 290, 191, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.layoutWidget = QtWidgets.QWidget(AbilityToPayDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 150, 492, 52))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 2, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout.addWidget(self.spinBox_2, 1, 3, 1, 1)

        self.retranslateUi(AbilityToPayDialog)
        QtCore.QMetaObject.connectSlotsByName(AbilityToPayDialog)

    def retranslateUi(self, AbilityToPayDialog):
        _translate = QtCore.QCoreApplication.translate
        AbilityToPayDialog.setWindowTitle(_translate("AbilityToPayDialog", "Ability To Pay"))
        self.pushButton_2.setText(_translate("AbilityToPayDialog", "Proceed to Community Control"))
        self.label_5.setText(_translate("AbilityToPayDialog", "Fine Amount:"))
        self.label_6.setText(_translate("AbilityToPayDialog", "Fines Suspended:"))
        self.label_7.setText(_translate("AbilityToPayDialog", "Jail Days:"))
        self.label_8.setText(_translate("AbilityToPayDialog", "Jail Days Suspended:"))
