# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/CaseInformation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CaseInformationDialog(object):
    def setupUi(self, CaseInformationDialog):
        CaseInformationDialog.setObjectName("CaseInformationDialog")
        CaseInformationDialog.resize(740, 484)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        CaseInformationDialog.setFont(font)
        self.pushButton = QtWidgets.QPushButton(CaseInformationDialog)
        self.pushButton.setGeometry(QtCore.QRect(470, 430, 158, 30))
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget = QtWidgets.QWidget(CaseInformationDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 601, 164))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.case_number = QtWidgets.QLineEdit(self.layoutWidget)
        self.case_number.setObjectName("case_number")
        self.gridLayout.addWidget(self.case_number, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.defendant_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.defendant_name.setObjectName("defendant_name")
        self.gridLayout.addWidget(self.defendant_name, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.plea_trial_date = QtWidgets.QDateEdit(self.layoutWidget)
        self.plea_trial_date.setMinimumDate(QtCore.QDate(2021, 1, 1))
        self.plea_trial_date.setCalendarPopup(True)
        self.plea_trial_date.setDate(QtCore.QDate.currentDate())
        self.plea_trial_date.setObjectName("plea_trial_date")
        self.gridLayout.addWidget(self.plea_trial_date, 2, 2, 1, 1)
        self.waived_counsel_checkbox = QtWidgets.QCheckBox(self.layoutWidget)
        self.waived_counsel_checkbox.setObjectName("waived_counsel_checkbox")
        self.gridLayout.addWidget(self.waived_counsel_checkbox, 3, 0, 1, 3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.counsel_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.counsel_name.setObjectName("counsel_name")
        self.gridLayout.addWidget(self.counsel_name, 4, 1, 1, 2)
        self.layoutWidget1 = QtWidgets.QWidget(CaseInformationDialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 230, 601, 161))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.ovi_checkbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.ovi_checkbox.setObjectName("ovi_checkbox")
        self.gridLayout_2.addWidget(self.ovi_checkbox, 1, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_2.addWidget(self.checkBox_2, 2, 0, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_2.addWidget(self.checkBox_3, 3, 0, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_2.addWidget(self.checkBox_4, 4, 0, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(CaseInformationDialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(640, 10, 89, 68))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 1, 0, 1, 1)

        self.retranslateUi(CaseInformationDialog)
        self.pushButton_3.clicked.connect(CaseInformationDialog.reject)
        self.pushButton_2.clicked.connect(self.case_number.clear)
        self.pushButton_2.clicked.connect(self.defendant_name.clear)
        self.pushButton_2.clicked.connect(self.counsel_name.clear)
        self.pushButton.clicked.connect(CaseInformationDialog.continue_dialog)
        self.pushButton.released.connect(CaseInformationDialog.close_window)
        self.waived_counsel_checkbox.toggled["bool"].connect(
            CaseInformationDialog.set_dialog
        )
        QtCore.QMetaObject.connectSlotsByName(CaseInformationDialog)
        CaseInformationDialog.setTabOrder(self.case_number, self.defendant_name)
        CaseInformationDialog.setTabOrder(self.defendant_name, self.plea_trial_date)
        CaseInformationDialog.setTabOrder(
            self.plea_trial_date, self.waived_counsel_checkbox
        )
        CaseInformationDialog.setTabOrder(
            self.waived_counsel_checkbox, self.counsel_name
        )
        CaseInformationDialog.setTabOrder(self.counsel_name, self.ovi_checkbox)
        CaseInformationDialog.setTabOrder(self.ovi_checkbox, self.checkBox_2)
        CaseInformationDialog.setTabOrder(self.checkBox_2, self.checkBox_3)
        CaseInformationDialog.setTabOrder(self.checkBox_3, self.checkBox_4)
        CaseInformationDialog.setTabOrder(self.checkBox_4, self.pushButton)
        CaseInformationDialog.setTabOrder(self.pushButton, self.pushButton_2)
        CaseInformationDialog.setTabOrder(self.pushButton_2, self.pushButton_3)

    def retranslateUi(self, CaseInformationDialog):
        _translate = QtCore.QCoreApplication.translate
        CaseInformationDialog.setWindowTitle(
            _translate("CaseInformationDialog", "Case Information")
        )
        self.pushButton.setText(_translate("CaseInformationDialog", "Continue"))
        self.label.setText(_translate("CaseInformationDialog", "Case Number:"))
        self.label_2.setText(_translate("CaseInformationDialog", "Defendant Name: "))
        self.label_3.setText(_translate("CaseInformationDialog", "Plea or Trial Date:"))
        self.waived_counsel_checkbox.setText(
            _translate("CaseInformationDialog", "Defendant waived right to counsel")
        )
        self.label_4.setText(_translate("CaseInformationDialog", "Counsel Name:"))
        self.label_5.setText(
            _translate("CaseInformationDialog", "Check All Boxes That Apply")
        )
        self.ovi_checkbox.setText(
            _translate("CaseInformationDialog", "Case Involves OVI Offense")
        )
        self.checkBox_2.setText(
            _translate("CaseInformationDialog", "Amendment to Charges by Prosecutor")
        )
        self.checkBox_3.setText(
            _translate("CaseInformationDialog", "Defendant is to be Committed to Jail")
        )
        self.checkBox_4.setText(
            _translate(
                "CaseInformationDialog", "License Suspension (Driving, Hunting, CCW)"
            )
        )
        self.pushButton_2.setText(_translate("CaseInformationDialog", "Clear Fields"))
        self.pushButton_3.setText(_translate("CaseInformationDialog", "Cancel"))
