# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/EntryPreviewDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EntryPreviewDialog(object):
    def setupUi(self, EntryPreviewDialog):
        EntryPreviewDialog.setObjectName("EntryPreviewDialog")
        EntryPreviewDialog.resize(822, 644)
        self.buttonBox = QtWidgets.QDialogButtonBox(EntryPreviewDialog)
        self.buttonBox.setGeometry(QtCore.QRect(710, 550, 81, 71))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.case_information_frame = QtWidgets.QFrame(EntryPreviewDialog)
        self.case_information_frame.setGeometry(QtCore.QRect(10, 10, 801, 111))
        self.case_information_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.case_information_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.case_information_frame.setLineWidth(2)
        self.case_information_frame.setObjectName("case_information_frame")
        self.layoutWidget = QtWidgets.QWidget(self.case_information_frame)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 781, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.entry_name_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.entry_name_label.setFont(font)
        self.entry_name_label.setObjectName("entry_name_label")
        self.gridLayout_2.addWidget(self.entry_name_label, 0, 1, 1, 1)
        self.case_no_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.case_no_label.setFont(font)
        self.case_no_label.setObjectName("case_no_label")
        self.gridLayout_2.addWidget(self.case_no_label, 0, 0, 1, 1)
        self.defendant_name_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.defendant_name_label.setFont(font)
        self.defendant_name_label.setObjectName("defendant_name_label")
        self.gridLayout_2.addWidget(self.defendant_name_label, 1, 0, 1, 1)
        self.counsel_name_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.counsel_name_label.setFont(font)
        self.counsel_name_label.setObjectName("counsel_name_label")
        self.gridLayout_2.addWidget(self.counsel_name_label, 2, 0, 1, 1)

        self.retranslateUi(EntryPreviewDialog)
        self.buttonBox.accepted.connect(EntryPreviewDialog.accept)
        self.buttonBox.rejected.connect(EntryPreviewDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(EntryPreviewDialog)

    def retranslateUi(self, EntryPreviewDialog):
        _translate = QtCore.QCoreApplication.translate
        EntryPreviewDialog.setWindowTitle(_translate("EntryPreviewDialog", "Entry Preview"))
        self.entry_name_label.setText(_translate("EntryPreviewDialog", "TextLabel"))
        self.case_no_label.setText(_translate("EntryPreviewDialog", "TextLabel"))
        self.defendant_name_label.setText(_translate("EntryPreviewDialog", "TextLabel"))
        self.counsel_name_label.setText(_translate("EntryPreviewDialog", "TextLabel"))
