# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\ExtraditionEntryDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExtraditionEntryDialog(object):
    def setupUi(self, ExtraditionEntryDialog):
        ExtraditionEntryDialog.setObjectName("ExtraditionEntryDialog")
        ExtraditionEntryDialog.resize(579, 438)
        self.layoutWidget_2 = QtWidgets.QWidget(ExtraditionEntryDialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(460, 20, 95, 151))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(20, 58, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.layoutWidget = QtWidgets.QWidget(ExtraditionEntryDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 15, 411, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(5, 5, 5, 5)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.defendant_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.defendant_name.setObjectName("defendant_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.defendant_name)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.case_no = QtWidgets.QLineEdit(self.layoutWidget)
        self.case_no.setObjectName("case_no")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.case_no)
        self.textBrowser = QtWidgets.QTextBrowser(ExtraditionEntryDialog)
        self.textBrowser.setGeometry(QtCore.QRect(10, 120, 401, 161))
        self.textBrowser.setObjectName("textBrowser")
        self.widget = QtWidgets.QWidget(ExtraditionEntryDialog)
        self.widget.setGeometry(QtCore.QRect(10, 290, 401, 141))
        self.widget.setObjectName("widget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.widget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.out_of_state_fugitive = QtWidgets.QRadioButton(self.widget)
        self.out_of_state_fugitive.setChecked(True)
        self.out_of_state_fugitive.setObjectName("out_of_state_fugitive")
        self.buttonGroup = QtWidgets.QButtonGroup(ExtraditionEntryDialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.out_of_state_fugitive)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.out_of_state_fugitive)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.defendant_hold_date = QtWidgets.QDateEdit(self.widget)
        self.defendant_hold_date.setMaximumDate(QtCore.QDate(2100, 12, 31))
        self.defendant_hold_date.setMinimumDate(QtCore.QDate(2021, 5, 31))
        self.defendant_hold_date.setCalendarPopup(True)
        self.defendant_hold_date.setDate(QtCore.QDate(2021, 5, 31))
        self.defendant_hold_date.setObjectName("defendant_hold_date")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.defendant_hold_date)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.defendant_hold_time = QtWidgets.QTimeEdit(self.widget)
        self.defendant_hold_time.setMinimumTime(QtCore.QTime(8, 0, 0))
        self.defendant_hold_time.setCalendarPopup(False)
        self.defendant_hold_time.setObjectName("defendant_hold_time")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.defendant_hold_time)
        self.out_of_county_warrant = QtWidgets.QRadioButton(self.widget)
        self.out_of_county_warrant.setObjectName("out_of_county_warrant")
        self.buttonGroup.addButton(self.out_of_county_warrant)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.out_of_county_warrant)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.state_county_requestor = QtWidgets.QLineEdit(self.widget)
        self.state_county_requestor.setObjectName("state_county_requestor")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.state_county_requestor)

        self.retranslateUi(ExtraditionEntryDialog)
        self.pushButton.clicked.connect(ExtraditionEntryDialog.createEntry)
        self.pushButton_2.clicked.connect(self.defendant_name.clear)
        self.pushButton_2.clicked.connect(self.case_no.clear)
        self.pushButton_3.clicked.connect(ExtraditionEntryDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ExtraditionEntryDialog)

    def retranslateUi(self, ExtraditionEntryDialog):
        _translate = QtCore.QCoreApplication.translate
        ExtraditionEntryDialog.setWindowTitle(_translate("ExtraditionEntryDialog", "Extradition Entry"))
        self.pushButton.setText(_translate("ExtraditionEntryDialog", "Create Entry"))
        self.pushButton_2.setText(_translate("ExtraditionEntryDialog", "Clear Fields"))
        self.pushButton_3.setText(_translate("ExtraditionEntryDialog", "Cancel"))
        self.label.setText(_translate("ExtraditionEntryDialog", "Defendant Name:"))
        self.label_2.setText(_translate("ExtraditionEntryDialog", "Case No.:"))
        self.textBrowser.setHtml(_translate("ExtraditionEntryDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Instructions: </span>The defendant is detained as a fugitive from another state, and is committed subject to bond.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- Ask if he/she waive\'s issuance of governor\'s warrant and habeas corpus pursuant to R.C. 2963.11-13.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- Inform the defendant that they shall report to court as directed if released upon bond.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- R.C. 51430.24 (check this statute) limits release on bond for parolee per sending state warrant. </p></body></html>"))
        self.out_of_state_fugitive.setText(_translate("ExtraditionEntryDialog", "Out-of-State Fugitive"))
        self.label_3.setText(_translate("ExtraditionEntryDialog", "Defendant hold until date:"))
        self.label_4.setText(_translate("ExtraditionEntryDialog", "Defendant hold until time:"))
        self.out_of_county_warrant.setText(_translate("ExtraditionEntryDialog", "Out-of-County Warrant"))
        self.label_5.setText(_translate("ExtraditionEntryDialog", "Requesting State/County:"))
