# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/FailureToAppearDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FailureToAppearDialog(object):
    def setupUi(self, FailureToAppearDialog):
        FailureToAppearDialog.setObjectName("FailureToAppearDialog")
        FailureToAppearDialog.resize(579, 438)
        self.layoutWidget_2 = QtWidgets.QWidget(FailureToAppearDialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(460, 20, 95, 151))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(20, 58, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.layoutWidget = QtWidgets.QWidget(FailureToAppearDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(5, 15, 411, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(5, 5, 5, 5)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.defendant_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.defendant_name.setObjectName("defendant_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.defendant_name)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.case_no = QtWidgets.QLineEdit(self.layoutWidget)
        self.case_no.setObjectName("case_no")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.case_no)
        self.widget = QtWidgets.QWidget(FailureToAppearDialog)
        self.widget.setGeometry(QtCore.QRect(21, 120, 391, 61))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 2)
        self.dateEdit = QtWidgets.QDateEdit(self.widget)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.primary_charge = QtWidgets.QComboBox(self.widget)
        self.primary_charge.setEnabled(True)
        self.primary_charge.setEditable(True)
        self.primary_charge.setObjectName("primary_charge")
        self.primary_charge.addItem("")
        self.primary_charge.addItem("")
        self.gridLayout.addWidget(self.primary_charge, 1, 2, 1, 1)

        self.retranslateUi(FailureToAppearDialog)
        self.pushButton.clicked.connect(FailureToAppearDialog.createEntry)
        self.pushButton_2.clicked.connect(self.defendant_name.clear)
        self.pushButton_2.clicked.connect(self.case_no.clear)
        self.pushButton_3.clicked.connect(FailureToAppearDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(FailureToAppearDialog)

    def retranslateUi(self, FailureToAppearDialog):
        _translate = QtCore.QCoreApplication.translate
        FailureToAppearDialog.setWindowTitle(_translate("FailureToAppearDialog", "Failure To Appear"))
        self.pushButton.setText(_translate("FailureToAppearDialog", "Create Entry"))
        self.pushButton_2.setText(_translate("FailureToAppearDialog", "Clear Fields"))
        self.pushButton_3.setText(_translate("FailureToAppearDialog", "Cancel"))
        self.label.setText(_translate("FailureToAppearDialog", "Defendant Name:"))
        self.label_2.setText(_translate("FailureToAppearDialog", "Case No.:"))
        self.label_3.setText(_translate("FailureToAppearDialog", "Scheduled Hearing/Apperance Date: "))
        self.label_4.setText(_translate("FailureToAppearDialog", "Charge:"))
        self.primary_charge.setItemText(0, _translate("FailureToAppearDialog", "OVI"))
        self.primary_charge.setItemText(1, _translate("FailureToAppearDialog", "Failure to Control"))
