# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(651, 600)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.FinalJudgmentEntryButton = QtWidgets.QPushButton(self.centralwidget)
        self.FinalJudgmentEntryButton.setGeometry(QtCore.QRect(30, 30, 171, 31))
        self.FinalJudgmentEntryButton.setObjectName("FinalJudgmentEntryButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 651, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionOptions = QtWidgets.QAction(MainWindow)
        self.actionOptions.setObjectName("actionOptions")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionExit_2 = QtWidgets.QAction(MainWindow)
        self.actionExit_2.setObjectName("actionExit_2")
        self.actionGeneral_Motion_Entry = QtWidgets.QAction(MainWindow)
        self.actionGeneral_Motion_Entry.setObjectName("actionGeneral_Motion_Entry")
        self.actionFail_to_Appear_Minor_Traffic_Offense = QtWidgets.QAction(MainWindow)
        self.actionFail_to_Appear_Minor_Traffic_Offense.setObjectName("actionFail_to_Appear_Minor_Traffic_Offense")
        self.actionOmnibus_Motion_Form = QtWidgets.QAction(MainWindow)
        self.actionOmnibus_Motion_Form.setObjectName("actionOmnibus_Motion_Form")
        self.actionJury_Instructions = QtWidgets.QAction(MainWindow)
        self.actionJury_Instructions.setObjectName("actionJury_Instructions")
        self.actionDialogs = QtWidgets.QAction(MainWindow)
        self.actionDialogs.setObjectName("actionDialogs")
        self.actionTemplates = QtWidgets.QAction(MainWindow)
        self.actionTemplates.setObjectName("actionTemplates")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionOptions)
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit_2)
        self.menuSettings.addAction(self.actionDialogs)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.FinalJudgmentEntryButton.clicked.connect(MainWindow.pushButtonDialog)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MuniEntry"))
        self.FinalJudgmentEntryButton.setText(_translate("MainWindow", "Final Judgment Entry"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOptions.setText(_translate("MainWindow", "Options"))
        self.actionExit.setText(_translate("MainWindow", "Templates"))
        self.actionExit_2.setText(_translate("MainWindow", "Exit"))
        self.actionGeneral_Motion_Entry.setText(_translate("MainWindow", "General Motion Entry"))
        self.actionFail_to_Appear_Minor_Traffic_Offense.setText(_translate("MainWindow", "Fail to Appear - Minor Traffic Offense"))
        self.actionOmnibus_Motion_Form.setText(_translate("MainWindow", "Omnibus Motion Form"))
        self.actionJury_Instructions.setText(_translate("MainWindow", "Jury Instructions"))
        self.actionDialogs.setText(_translate("MainWindow", "Dialogs"))
        self.actionTemplates.setText(_translate("MainWindow", "Templates"))
