from PyQt5.QtWidgets import QDialog
from typing import Any


class BaseDialog(QDialog):
    def __init__(self, parent: QDialog = ...) -> None: ...
    def modify_view(self) -> Any: ...
    def create_dialog_slot_functions(self) -> None: ...
    def connect_signals_to_slots(self) -> Any: ...
    def transfer_view_data_to_model(self, model_class: type[Any]) -> None: ...


class CriminalBaseDialog(BaseDialog):
    case_table: Any
    judicial_officer: Any
    cms_case: Any
    entry_case_information: Any
    criminal_charge: Any
    popup_dialog: Any
    def __init__(self, judicial_officer, cms_case: Any | None = ..., case_table: Any | None = ..., parent: Any | None = ...) -> None: ...
    def load_cms_data_to_view(self) -> Any: ...
    def update_entry_case_information(self) -> Any: ...
    def perform_info_checks(self) -> None: ...
    def add_charge_to_grid(self) -> None: ...
    def start_jail_only_dialog(self) -> None: ...