from PyQt5.QtWidgets import QDialog
from package.controllers.signal_connectors import AddChargeDialogSignalConnector as AddChargeDialogSignalConnector, AmendChargeDialogSignalConnector as AmendChargeDialogSignalConnector
from package.controllers.slot_functions import AddChargeDialogSlotFunctions as AddChargeDialogSlotFunctions, AmendChargeDialogSlotFunctions as AmendChargeDialogSlotFunctions
from package.controllers.view_modifiers import AddChargeDialogViewModifier as AddChargeDialogViewModifier, AmendChargeDialogViewModifier as AmendChargeDialogViewModifier
from package.database_controllers.databases import open_db_connection as open_db_connection, query_offense_statute_data as query_offense_statute_data
from package.models.criminal_charge_models import AmendOffenseDetails as AmendOffenseDetails
from package.views.add_charge_dialog_ui import Ui_AddChargeDialog as Ui_AddChargeDialog
from package.views.amend_charge_dialog_ui import Ui_AmendChargeDialog as Ui_AmendChargeDialog
from typing import Any

class BaseChargeDialog(QDialog):
    main_dialog: Any
    functions: Any
    def __init__(self, main_dialog, parent: Any | None = ...) -> None: ...
    charges_database: Any
    def set_database(self) -> None: ...
    def load_statute_and_offense_choice_boxes(self) -> None: ...

class AddChargeDialog(BaseChargeDialog, Ui_AddChargeDialog):
    def modify_view(self): ...
    def create_dialog_slot_functions(self): ...
    def connect_signals_to_slots(self): ...

class AmendChargeDialog(BaseChargeDialog, Ui_AmendChargeDialog):
    amend_offense_details: Any
    charge: Any
    current_offense_name: Any
    def __init__(self, main_dialog, parent: Any | None = ...) -> None: ...
    def modify_view(self): ...
    def create_dialog_slot_functions(self): ...
    def connect_signals_to_slots(self): ...
