from package.controllers.slot_functions import BaseDialogSlotFunctions as BaseDialogSlotFunctions, BondHearingDialogSlotFunctions as BondHearingDialogSlotFunctions

class BaseDialogSignalConnector:
    def __init__(self, dialog) -> None: ...
    def connect_main_dialog_common_signals(self, dialog) -> None: ...
    def connect_fra_signals(self, dialog) -> None: ...
    def connect_plea_all_button_signals(self, dialog) -> None: ...
    def connect_court_cost_signals(self, dialog) -> None: ...
    def connect_main_dialog_additional_condition_signals(self, dialog) -> None: ...
    def connect_condition_dialog_main_signals(self, dialog) -> None: ...
    def connect_jail_frame_signals(self, dialog) -> None: ...
    def connect_community_service_days_update(self, dialog) -> None: ...
    def connect_statute_and_offense_boxes(self, dialog): ...

class AddChargeDialogSignalConnector(BaseDialogSignalConnector):
    def __init__(self, dialog) -> None: ...

class AmendChargeDialogSignalConnector(BaseDialogSignalConnector):
    def __init__(self, dialog) -> None: ...

class FineOnlyDialogSignalConnector(BaseDialogSignalConnector):
    def __init__(self, dialog) -> None: ...

class PleaOnlyDialogSignalConnector(BaseDialogSignalConnector):
    def __init__(self, dialog) -> None: ...

class JailCCDialogSignalConnector(BaseDialogSignalConnector):
    def __init__(self, dialog) -> None: ...

class DiversionDialogSignalConnector(BaseDialogSignalConnector):
    def __init__(self, dialog) -> None: ...

class NotGuiltyBondDialogSignalConnector(BaseDialogSignalConnector):
    def __init__(self, dialog) -> None: ...

class NoPleaBondDialogSignalConnector(BaseDialogSignalConnector):
    def __init__(self, dialog) -> None: ...

class BondHearingDialogSignalConnector(BaseDialogSignalConnector):
    def __init__(self, dialog) -> None: ...

class ProbationViolationBondDialogSignalConnector(BaseDialogSignalConnector):
    def __init__(self, dialog) -> None: ...

class FailureToAppearDialogSignalConnector(BaseDialogSignalConnector):
    def __init__(self, dialog) -> None: ...

class AddConditionsDialogSignalConnector(BaseDialogSignalConnector):
    def __init__(self, dialog) -> None: ...

class AddJailOnlyDialogSignalConnector(BaseDialogSignalConnector):
    def __init__(self, dialog) -> None: ...

class AddCommunityControlDialogSignalConnector(BaseDialogSignalConnector):
    def __init__(self, dialog) -> None: ...
    def connect_community_control_dialog_specific_signals(self, dialog) -> None: ...

class AddSpecialBondConditionsDialogSignalConnector(BaseDialogSignalConnector):
    def __init__(self, dialog) -> None: ...
