from package.updaters.base_updaters import BaseDialogUpdater as BaseDialogUpdater
from typing import Any, TypeVar

BDU = TypeVar('BDU', bound=BaseDialogUpdater)

class CaseInformationUpdater:
    view: Any
    model: Any
    def __init__(self, updater: BDU) -> None: ...
    def update_defendant(self) -> None: ...
    def update_defense_counsel(self) -> None: ...

class CourtCostsUpdater:
    view: Any
    model: Any
    def __init__(self, updater: BDU) -> None: ...
    def calculate_court_costs(self) -> int: ...
    def set_max_court_costs(self, charge: type[Any], court_costs: int) -> int: ...

class FinesUpdater:
    view: Any
    model: Any
    def __init__(self, updater: BDU) -> None: ...
    def calculate_total_fines(self) -> int: ...
    def calculate_total_fines_suspended(self) -> int: ...

class JailDataUpdater:
    view: Any
    model: Any
    def __init__(self, updater: BDU) -> None: ...
    def update_jail_time_credit(self) -> None: ...
    def set_jail_time_credit(self) -> int: ...
    def set_all_jail_day_totals(self) -> None: ...
    def calculate_total_jail_days_to_serve(self) -> int: ...
    def calculate_total_jail_days_imposed(self) -> int: ...
    def calculate_total_jail_days_suspended(self) -> int: ...
