from munientry.builders.base_dialogs import CriminalBaseDialog as CriminalBaseDialog
from munientry.updaters.charge_grid_updaters import DiversionGridModelUpdater as DiversionGridModelUpdater, FineOnlyGridModelUpdater as FineOnlyGridModelUpdater, JailCCGridModelUpdater as JailCCGridModelUpdater, NotGuiltyGridModelUpdater as NotGuiltyGridModelUpdater, PleaOnlyGridModelUpdater as PleaOnlyGridModelUpdater
from munientry.updaters.general_updaters import CaseInformationUpdater as CaseInformationUpdater, CourtCostsUpdater as CourtCostsUpdater, FinesUpdater as FinesUpdater, JailDataUpdater as JailDataUpdater
from typing import Any, TypeVar

BD = TypeVar('BD', bound=CriminalBaseDialog)

class BaseDialogUpdater:
    view: Any
    model: Any
    def __init__(self, dialog: BD) -> None: ...

class DiversionDialogUpdater(BaseDialogUpdater):
    def __init__(self, dialog: BD) -> None: ...
    def update_case_information(self) -> CaseInformationUpdater: ...
    def update_diversion_information(self) -> None: ...
    def update_model_with_charge_grid_data(self) -> DiversionGridModelUpdater: ...

class JailCCDialogUpdater(BaseDialogUpdater):
    def __init__(self, dialog: BD) -> None: ...
    def update_case_information(self) -> CaseInformationUpdater: ...
    def update_model_with_charge_grid_data(self) -> JailCCGridModelUpdater: ...
    def update_court_costs(self) -> CourtCostsUpdater: ...
    def update_fines(self) -> FinesUpdater: ...
    def update_jail_data(self) -> JailDataUpdater: ...

class FineOnlyDialogUpdater(BaseDialogUpdater):
    def __init__(self, dialog: BD) -> None: ...
    def update_case_information(self) -> CaseInformationUpdater: ...
    def update_model_with_charge_grid_data(self) -> FineOnlyGridModelUpdater: ...
    def update_court_costs(self) -> CourtCostsUpdater: ...
    def update_fines(self) -> FinesUpdater: ...
    def update_jail_time_credit_for_fines(self) -> None: ...

class PleaOnlyDialogUpdater(BaseDialogUpdater):
    def __init__(self, dialog: BD) -> None: ...
    def update_case_information(self) -> CaseInformationUpdater: ...
    def update_model_with_charge_grid_data(self) -> PleaOnlyGridModelUpdater: ...
    def update_model_with_future_sentencing_and_bond(self) -> None: ...

class NotGuiltyBondDialogUpdater(BaseDialogUpdater):
    def __init__(self, dialog: BD) -> None: ...
    def update_case_information(self) -> CaseInformationUpdater: ...
    def update_model_with_charge_grid_data(self) -> NotGuiltyGridModelUpdater: ...
    def update_bond_conditions(self) -> None: ...
