from munientry.updaters.general_updaters import CaseInformationUpdater as CaseInformationUpdater
from typing import Any

class NoPleaBondDialogUpdater:
    view: Any
    model: Any
    def __init__(self, dialog) -> None: ...
    def update_case_information(self) -> CaseInformationUpdater: ...
    def update_bond_conditions(self) -> None: ...

class BondHearingDialogUpdater:
    view: Any
    model: Any
    def __init__(self, dialog) -> None: ...
    def update_case_information(self) -> CaseInformationUpdater: ...
    def update_bond_conditions(self) -> None: ...

class FailureToAppearDialogUpdater:
    view: Any
    model: Any
    def __init__(self, dialog) -> None: ...
    def update_case_information(self) -> CaseInformationUpdater: ...
    def update_fta_conditions(self) -> None: ...

class ProbationViolationBondDialogUpdater:
    view: Any
    model: Any
    def __init__(self, dialog) -> None: ...
    def update_case_information(self) -> CaseInformationUpdater: ...
    def update_model_with_probable_cause_information(self) -> None: ...
    def update_bond_conditions(self) -> None: ...
