from .custom_widgets import NoScrollComboBox as NoScrollComboBox, NoScrollDateEdit as NoScrollDateEdit
from typing import Any

class Ui_AddCommunityControlDialog:
    gridLayout_7: Any
    scrollArea: Any
    scrollAreaWidgetContents: Any
    gridLayout_5: Any
    add_conditions_Button: Any
    cancel_Button: Any
    community_control_frame: Any
    gridLayout_3: Any
    driver_intervention_program_checkBox: Any
    house_arrest_checkBox: Any
    label_4: Any
    alcohol_monitoring_checkBox: Any
    label_8: Any
    pay_restitution_checkBox: Any
    mental_health_evaluation_checkBox: Any
    gps_exclusion_checkBox: Any
    house_arrest_time_box: Any
    label_16: Any
    specialized_docket_checkBox: Any
    specialized_docket_box: Any
    gps_exclusion_radius_box: Any
    gps_exclusion_location_box: Any
    line_2: Any
    line_19: Any
    interlock_vehicles_checkBox: Any
    line_3: Any
    line_4: Any
    cs_label: Any
    label_12: Any
    community_control_community_service_checkBox: Any
    other_community_control_checkBox: Any
    community_control_community_service_hours_box: Any
    other_community_control_conditions_box: Any
    label_25: Any
    community_control_no_contact_checkBox: Any
    domestic_violence_program_checkBox: Any
    community_control_no_contact_with_box: Any
    label_2: Any
    test: Any
    line: Any
    community_control_term_of_control_box: Any
    community_control_type_of_control_box: Any
    daily_reporting_checkBox: Any
    line_6: Any
    label_7: Any
    label_6: Any
    antitheft_checkBox: Any
    community_control_not_within_500_feet_checkBox: Any
    anger_management_checkBox: Any
    alcohol_evaluation_checkBox: Any
    community_control_not_within_500_feet_person_box: Any
    alcohol_monitoring_court_pay_checkBox: Any
    alcohol_monitoring_time_box: Any
    pay_restitution_to_box: Any
    pay_restitution_amount_box: Any
    other_conditions_frame: Any
    gridLayout_9: Any
    other_conditions_textEdit: Any
    label_5: Any
    license_suspension_frame: Any
    gridLayout_2: Any
    label_9: Any
    license_type_box: Any
    als_terminated_checkBox: Any
    label_18: Any
    license_suspension_date_box: Any
    remedial_driving_class_checkBox: Any
    label_21: Any
    term_of_suspension_box: Any
    label_24: Any
    victim_notification_frame: Any
    gridLayout_11: Any
    victim_prosecutor_notification_checkBox: Any
    victim_reparation_checkBox: Any
    fingerprinting_checkBox: Any
    label_29: Any
    impoundment_frame: Any
    gridLayout_10: Any
    label_13: Any
    label_3: Any
    vehicle_make_model_box: Any
    label_28: Any
    label_20: Any
    vehicle_license_plate_box: Any
    vehicle_impound_time_box: Any
    label_31: Any
    vehicle_impound_action_box: Any
    case_banner_frame: Any
    gridLayout_4: Any
    charges_gridLayout: Any
    offense_label_1: Any
    label_14: Any
    label_19: Any
    filler_frame: Any
    community_service_frame: Any
    gridLayout: Any
    label_26: Any
    community_service_days_to_complete_box: Any
    community_service_hours_ordered_box: Any
    label_22: Any
    community_service_date_to_complete_box: Any
    label: Any
    label_15: Any
    def setupUi(self, AddCommunityControlDialog) -> None: ...
    def retranslateUi(self, AddCommunityControlDialog) -> None: ...
