from PyQt5 import QtGui
from PyQt5.QtCore import QDate, QDateTime as QDateTime, QEvent as QEvent, QTime
from PyQt5.QtGui import QFont as QFont
from PyQt5.QtWidgets import QCheckBox, QComboBox, QDateEdit, QDateTimeEdit as QDateTimeEdit, QInputDialog, QLabel, QLineEdit, QMessageBox, QPushButton, QTimeEdit
from typing import Any

def return_attorney_data_from_excel(excel_file: str) -> list: ...

TODAY: Any
TODAY_STRING: Any
ATTORNEY_LIST: Any

class NoScrollComboBox(QComboBox):
    def __init__(self, parent: Any | None = ...) -> None: ...
    def wheelEvent(self, event) -> None: ...

class NoScrollDateEdit(QDateEdit):
    def __init__(self, parent: Any | None = ...) -> None: ...
    def get_date(self) -> str: ...
    def set_date(self, date_str: str) -> QDate: ...
    def wheelEvent(self, event) -> None: ...

class NoScrollTimeEdit(QTimeEdit):
    def __init__(self, parent: Any | None = ...) -> None: ...
    def get_time(self) -> str: ...
    def set_time(self, time_str: str) -> QTime: ...
    def wheelEvent(self, event) -> None: ...

class ExtendedComboBox(QComboBox):
    pFilterModel: Any
    completer: Any
    def __init__(self, parent: Any | None = ...) -> None: ...
    def show_menu(self, pos) -> None: ...
    def delete_case(self) -> None: ...
    def keyPressEvent(self, event: QtGui.QKeyEvent) -> None: ...
    def on_completer_activated(self, text) -> None: ...
    def setModel(self, model) -> None: ...
    def setModelColumn(self, column) -> None: ...

class DefenseCounselComboBox(NoScrollComboBox):
    def __init__(self, parent: Any | None = ...) -> None: ...
    def load_attorneys(self) -> None: ...

class StatuteLineEdit(QLabel):
    statute: Any
    def __init__(self, statute: str = ..., parent: Any | None = ...) -> None: ...
    def get_text(self) -> str: ...
    def set_up_widget(self, statute: str): ...
    def set_url_link(self, statute: str) -> str: ...

class DegreeComboBox(NoScrollComboBox):
    def __init__(self, degree, parent: Any | None = ...) -> None: ...
    def set_up_widget(self, degree) -> None: ...

class PleaComboBox(NoScrollComboBox):
    column: Any
    def __init__(self, column, parent: Any | None = ...) -> None: ...
    def set_up_widget(self) -> None: ...

class FindingComboBox(NoScrollComboBox):
    def __init__(self, parent: Any | None = ...) -> None: ...
    def set_up_widget(self) -> None: ...

class ChargeGridDeleteButton(QPushButton):
    column_index: Any
    dialog: Any
    charge: Any
    def __init__(self, column_index, charge, dialog, parent: Any | None = ...) -> None: ...
    def set_up_widget(self) -> None: ...
    def delete_charge_from_grid_and_charges_list(self) -> None: ...

class ChargeGridAmendButton(QPushButton):
    column_index: Any
    dialog: Any
    charge: Any
    def __init__(self, column_index, charge, dialog, parent: Any | None = ...) -> None: ...
    def set_up_widget(self) -> None: ...

class AlliedCheckbox(QCheckBox):
    column_index: Any
    dialog: Any
    def __init__(self, column_index, dialog, parent: Any | None = ...) -> None: ...
    def set_up_widget(self) -> None: ...
    def set_to_allied(self) -> None: ...

class DismissedCheckbox(QCheckBox):
    dialog: Any
    column_index: Any
    def __init__(self, column_index, dialog, parent: Any | None = ...) -> None: ...
    def set_up_widget(self) -> None: ...
    def set_to_dismissed(self) -> None: ...

class RequiredBox(QMessageBox):
    message: Any
    def __init__(self, message, parent: Any | None = ...) -> None: ...
    def set_up_widget(self) -> None: ...

class InfoBox(QMessageBox):
    def __init__(self, parent: Any | None = ...) -> None: ...
    def set_up_widget(self) -> None: ...

class WarningBox(QMessageBox):
    message: Any
    def __init__(self, message, parent: Any | None = ...) -> None: ...
    def set_up_widget(self) -> None: ...

class TwoChoiceQuestionBox(QMessageBox):
    message: Any
    def __init__(self, message, yes_choice, no_choice, parent: Any | None = ...) -> None: ...
    def set_up_widget(self, yes_choice, no_choice) -> None: ...

class DataInputBox(QInputDialog):
    message: Any
    def __init__(self, message, parent: Any | None = ...) -> None: ...
    box: Any
    def set_up_widget(self) -> None: ...

class JailWarningBox(QMessageBox):
    message: Any
    def __init__(self, message, parent: Any | None = ...) -> None: ...
    def set_up_widget(self) -> None: ...

class IntegerValidator(QLineEdit):
    validator: Any
    def __init__(self, parent: Any | None = ...) -> None: ...

class ChargeGridIntegerWidget(IntegerValidator):
    def __init__(self, parent: Any | None = ...) -> None: ...
    def set_up_widget(self) -> None: ...

class FineLineEdit(ChargeGridIntegerWidget):
    def __init__(self, offense: Any | None = ..., parent: Any | None = ...) -> None: ...
    def set_fine_amount(self, offense) -> None: ...

class FineSuspendedLineEdit(ChargeGridIntegerWidget):
    def __init__(self, parent: Any | None = ...) -> None: ...

class JailLineEdit(ChargeGridIntegerWidget):
    def __init__(self, offense: Any | None = ..., parent: Any | None = ...) -> None: ...

class JailSuspendedLineEdit(ChargeGridIntegerWidget):
    def __init__(self, parent: Any | None = ...) -> None: ...

class JailTimeCreditLineEdit(ChargeGridIntegerWidget):
    def __init__(self, parent: Any | None = ...) -> None: ...

def main() -> None: ...
