from .custom_widgets import NoScrollComboBox as NoScrollComboBox, NoScrollDateEdit as NoScrollDateEdit
from typing import Any

class Ui_DiversionPleaDialog:
    verticalLayout: Any
    scrollArea: Any
    scrollAreaWidgetContents_2: Any
    gridLayout_2: Any
    diversion_frame: Any
    gridLayout_8: Any
    label_6: Any
    marijuana_diversion_radioButton: Any
    buttonGroup: Any
    line_2: Any
    diversion_jail_imposed_checkBox: Any
    diversion_jail_report_date_box: Any
    diversion_jail_report_date_label: Any
    label_23: Any
    diversion_fine_pay_date_box: Any
    other_conditions_textEdit: Any
    other_conditions_checkBox: Any
    jail_report_date_note_label: Any
    theft_diversion_radioButton: Any
    other_diversion_radioButton: Any
    line_7: Any
    label_9: Any
    frame: Any
    verticalLayout_2: Any
    gridLayout_3: Any
    no_contest_all_Button: Any
    guilty_all_Button: Any
    add_charge_Button: Any
    charges_gridLayout: Any
    label_5: Any
    label_10: Any
    label_20: Any
    label_14: Any
    plea_label_1: Any
    label_12: Any
    offense_label_1: Any
    label_19: Any
    label_8: Any
    label_17: Any
    label_7: Any
    label_4: Any
    label_25: Any
    line: Any
    case_name_Frame: Any
    gridLayout: Any
    appearance_reason_box: Any
    label_24: Any
    label_3: Any
    defense_counsel_type_box: Any
    defense_counsel_name_box: Any
    defense_counsel_waived_checkBox: Any
    clear_fields_case_Button: Any
    case_number_lineEdit: Any
    cancel_Button: Any
    label_26: Any
    defendant_last_name_lineEdit: Any
    label_27: Any
    defendant_first_name_lineEdit: Any
    plea_trial_date: Any
    label: Any
    label_2: Any
    line_3: Any
    fra_frame: Any
    formLayout_2: Any
    label_21: Any
    fra_in_file_box: Any
    label_22: Any
    fra_in_court_box: Any
    frame_3: Any
    gridLayout_4: Any
    create_entry_Button: Any
    close_dialog_Button: Any
    def setupUi(self, DiversionPleaDialog) -> None: ...
    def retranslateUi(self, DiversionPleaDialog) -> None: ...
