from .custom_widgets import NoScrollComboBox as NoScrollComboBox, NoScrollDateEdit as NoScrollDateEdit
from typing import Any

class Ui_FailureToAppearDialog:
    gridLayout_8: Any
    frame_4: Any
    gridLayout_4: Any
    scrollArea: Any
    scrollAreaWidgetContents: Any
    gridLayout_2: Any
    case_name_Frame: Any
    gridLayout: Any
    label_2: Any
    plea_trial_date: Any
    label_26: Any
    label_24: Any
    defense_counsel_type_box: Any
    defense_counsel_waived_checkBox: Any
    defense_counsel_name_box: Any
    clear_fields_case_Button: Any
    defendant_first_name_lineEdit: Any
    defendant_last_name_lineEdit: Any
    label_11: Any
    cancel_Button: Any
    label_3: Any
    label: Any
    case_number_lineEdit: Any
    line: Any
    appearance_reason_box: Any
    frame_5: Any
    gridLayout_7: Any
    gridLayout_5: Any
    bond_type_label: Any
    bond_type_box: Any
    bond_amount_label: Any
    bond_amount_box: Any
    label_5: Any
    set_bond_checkBox: Any
    frame_8: Any
    gridLayout_10: Any
    create_entry_Button: Any
    close_dialog_Button: Any
    frame: Any
    gridLayout_6: Any
    label_4: Any
    gridLayout_3: Any
    non_resident_license_checkBox: Any
    supplemental_summons_checkBox: Any
    bond_forfeited_checkBox: Any
    set_no_trial_checkBox: Any
    operator_license_checkBox: Any
    proof_of_service_checkBox: Any
    registration_block_checkBox: Any
    arrest_warrant_radius_box: Any
    surety_appear_checkBox: Any
    arrest_warrant_checkBox: Any
    arrest_warrant_radius_label: Any
    def setupUi(self, FailureToAppearDialog) -> None: ...
    def retranslateUi(self, FailureToAppearDialog) -> None: ...
