from .custom_widgets import NoScrollComboBox as NoScrollComboBox, NoScrollDateEdit as NoScrollDateEdit
from typing import Any

class Ui_JailCCPleaDialog:
    verticalLayout: Any
    scrollArea: Any
    scrollAreaWidgetContents_2: Any
    gridLayout_4: Any
    case_name_Frame: Any
    gridLayout: Any
    plea_trial_date: Any
    label_3: Any
    label_24: Any
    defense_counsel_type_box: Any
    label: Any
    defense_counsel_waived_checkBox: Any
    line_2: Any
    cancel_Button: Any
    label_27: Any
    appearance_reason_box: Any
    defense_counsel_name_box: Any
    label_2: Any
    defendant_first_name_lineEdit: Any
    label_26: Any
    defendant_last_name_lineEdit: Any
    case_number_lineEdit: Any
    clear_fields_case_Button: Any
    offense_of_violence_checkBox: Any
    victim_statements_checkBox: Any
    costs_frame: Any
    gridLayout_5: Any
    label_11: Any
    court_costs_box: Any
    label_9: Any
    ability_to_pay_box: Any
    label_18: Any
    balance_due_date: Any
    costs_and_fines_Button: Any
    frame_6: Any
    gridLayout_2: Any
    victim_notification_checkBox: Any
    impoundment_checkBox: Any
    community_control_checkBox: Any
    license_suspension_checkBox: Any
    community_service_checkBox: Any
    add_conditions_label: Any
    add_conditions_Button: Any
    other_conditions_checkBox: Any
    jail_time_credit_frame: Any
    gridLayout_6: Any
    companion_cases_sentence_label: Any
    companion_cases_sentence_box: Any
    jail_time_credit_apply_box: Any
    jail_time_credit_label: Any
    label_6: Any
    label_16: Any
    in_jail_box: Any
    jail_time_credit_box: Any
    label_13: Any
    companion_cases_box: Any
    add_companion_cases_checkBox: Any
    add_jail_report_Button: Any
    line_3: Any
    jail_checkBox: Any
    fra_frame: Any
    formLayout_2: Any
    label_21: Any
    fra_in_file_box: Any
    label_22: Any
    fra_in_court_box: Any
    frame_2: Any
    gridLayout_7: Any
    create_entry_Button: Any
    close_dialog_Button: Any
    frame: Any
    verticalLayout_2: Any
    gridLayout_3: Any
    no_contest_all_Button: Any
    guilty_all_Button: Any
    add_charge_Button: Any
    charges_gridLayout: Any
    label_5: Any
    label_10: Any
    label_20: Any
    label_14: Any
    plea_label_1: Any
    label_12: Any
    offense_label_1: Any
    label_19: Any
    label_8: Any
    label_17: Any
    label_7: Any
    label_4: Any
    label_25: Any
    line: Any
    def setupUi(self, JailCCPleaDialog) -> None: ...
    def retranslateUi(self, JailCCPleaDialog) -> None: ...
