from .custom_widgets import ExtendedComboBox as ExtendedComboBox
from typing import Any

class Ui_MainWindow:
    centralwidget: Any
    gridLayout_6: Any
    gridLayout_5: Any
    gridLayout_3: Any
    reload_cases_Button: Any
    final_pretrial_radioButton: Any
    label_3: Any
    pleas_cases_box: Any
    pcvh_fcvh_radioButton: Any
    slated_radioButton: Any
    trials_to_court_radioButton: Any
    trials_to_court_cases_box: Any
    pcvh_fcvh_cases_box: Any
    arraignments_cases_box: Any
    arraignments_radioButton: Any
    slated_cases_box: Any
    final_pretrial_cases_box: Any
    pleas_radioButton: Any
    judicial_officer_gridLayout: Any
    judicial_officer_frame: Any
    gridLayout: Any
    pelanda_radioButton: Any
    bunner_radioButton: Any
    kudela_radioButton: Any
    judicial_officer_label: Any
    hemmeter_radioButton: Any
    rohrer_radioButton: Any
    line: Any
    tabWidget: Any
    crimTab: Any
    gridLayout_2: Any
    FineOnlyPleaButton: Any
    FailureToAppearButton: Any
    NotGuiltyBondButton: Any
    JailCCPleaButton: Any
    NoPleaBondButton: Any
    BondHearingButton: Any
    DiversionButton: Any
    PleaOnlyButton: Any
    ProbationViolationBondButton: Any
    schedulingTab: Any
    gridLayout_4: Any
    pushButton_12: Any
    rohrer_schedulingEntryButton: Any
    hemmeter_schedulingEntryButton: Any
    line_2: Any
    label: Any
    menubar: Any
    menuFile: Any
    menuSettings: Any
    menuView: Any
    statusbar: Any
    actionOpen: Any
    actionOptions: Any
    actionExit: Any
    menu_file_exit: Any
    actionGeneral_Motion_Entry: Any
    actionFail_to_Appear_Minor_Traffic_Offense: Any
    actionOmnibus_Motion_Form: Any
    actionJury_Instructions: Any
    actioncontrollers: Any
    actionTemplates: Any
    def setupUi(self, MainWindow) -> None: ...
    def retranslateUi(self, MainWindow) -> None: ...
