from .custom_widgets import NoScrollComboBox as NoScrollComboBox, NoScrollDateEdit as NoScrollDateEdit
from typing import Any

class Ui_NoPleaBondDialog:
    gridLayout_8: Any
    frame_4: Any
    gridLayout_4: Any
    scrollArea: Any
    scrollAreaWidgetContents: Any
    gridLayout_9: Any
    case_name_Frame: Any
    gridLayout: Any
    label: Any
    plea_trial_date: Any
    defendant_first_name_lineEdit: Any
    defense_counsel_name_box: Any
    defense_counsel_type_box: Any
    defense_counsel_waived_checkBox: Any
    defendant_last_name_lineEdit: Any
    cancel_Button: Any
    label_26: Any
    label_3: Any
    clear_fields_case_Button: Any
    label_2: Any
    label_11: Any
    case_number_lineEdit: Any
    label_24: Any
    line_2: Any
    appearance_reason_box: Any
    frame_2: Any
    gridLayout_7: Any
    vehicle_seizure_checkBox: Any
    admin_license_suspension_checkBox: Any
    label_10: Any
    domestic_violence_checkBox: Any
    custodial_supervision_checkBox: Any
    no_contact_checkBox: Any
    other_conditions_checkBox: Any
    add_special_conditions_Button: Any
    frame_8: Any
    gridLayout_10: Any
    close_dialog_Button: Any
    create_entry_Button: Any
    frame_7: Any
    gridLayout_2: Any
    label_7: Any
    alcohol_drugs_assessment_checkBox: Any
    no_alcohol_drugs_checkBox: Any
    monitoring_type_box: Any
    specialized_docket_type_box: Any
    specialized_docket_checkBox: Any
    monitoring_checkBox: Any
    mental_health_assessment_checkBox: Any
    alcohol_test_kiosk_checkBox: Any
    comply_protection_order_checkBox: Any
    frame_5: Any
    gridLayout_5: Any
    label_9: Any
    bond_type_box: Any
    label_8: Any
    bond_amount_box: Any
    label_5: Any
    def setupUi(self, NoPleaBondDialog) -> None: ...
    def retranslateUi(self, NoPleaBondDialog) -> None: ...
