from .custom_widgets import NoScrollComboBox as NoScrollComboBox, NoScrollDateEdit as NoScrollDateEdit
from typing import Any

class Ui_SchedulingEntryDialog:
    gridLayout_8: Any
    frame_4: Any
    gridLayout_4: Any
    scrollArea: Any
    scrollAreaWidgetContents: Any
    gridLayout_2: Any
    case_name_Frame: Any
    gridLayout: Any
    label: Any
    label_26: Any
    defendant_last_name_lineEdit: Any
    cancel_Button: Any
    label_3: Any
    clear_fields_case_Button: Any
    defendant_first_name_lineEdit: Any
    plea_trial_date: Any
    label_2: Any
    case_number_lineEdit: Any
    label_24: Any
    label_6: Any
    defense_counsel_name_box: Any
    frame_6: Any
    gridLayout_6: Any
    label_12: Any
    label_11: Any
    arrest_summons_date_box: Any
    label_10: Any
    highest_charge_box: Any
    label_14: Any
    line: Any
    label_13: Any
    speedy_trial_date_label: Any
    days_in_jail_lineEdit: Any
    label_15: Any
    continuance_days_lineEdit: Any
    frame_5: Any
    gridLayout_5: Any
    four_week_pretrial_radioButton: Any
    buttonGroup: Any
    final_pretrial_time_box: Any
    three_week_pretrial_radioButton: Any
    label_5: Any
    no_pretrial_radioButton: Any
    two_week_pretrial_radioButton: Any
    pretrial_dateEdit: Any
    label_7: Any
    trial_dateEdit: Any
    label_9: Any
    pretrial_date_label: Any
    label_4: Any
    final_pretrial_dateEdit: Any
    label_16: Any
    frame_8: Any
    gridLayout_10: Any
    close_dialog_Button: Any
    create_entry_Button: Any
    def setupUi(self, SchedulingEntryDialog) -> None: ...
    def retranslateUi(self, SchedulingEntryDialog) -> None: ...
