def create_daily_case_list_tables_sql_query(table: str) -> str: ...
def create_charges_table_sql_query() -> str: ...
def insert_daily_case_list_tables_sql_query(table: str, case: object) -> str: ...
def insert_charges_sql_query(table: str, charge: object) -> str: ...
def delete_table_sql_query(table: str) -> str: ...
def select_case_data_sql_query(table: str, case_number: str) -> str: ...
def select_distinct_offense_statute_sql_query() -> str: ...
def select_distinct_def_last_def_first_case_number_sql_query(table: str) -> str: ...
def select_statute_from_charges_for_offense_type_sql_query() -> str: ...
